// Mini-app configuration types
// Matches the JSON structure generated by buildMiniAppConfigPrompt in src/lib/ai/prompts.ts

export interface KpiMetric {
  label: string;
  value: string | number;
  trend?: string;
  trendDirection?: "up" | "down";
}

export interface KpiCardsSection {
  id: string;
  type: "kpi_cards";
  title: string;
  metrics: KpiMetric[];
}

export interface DonutChartDataPoint {
  label: string;
  value: number;
  color?: string;
}

export interface DonutChartSection {
  id: string;
  type: "donut_chart";
  title: string;
  data: DonutChartDataPoint[];
}

export interface BarChartSection {
  id: string;
  type: "bar_chart";
  title: string;
  xAxis?: string;
  yAxis?: string;
  data: Record<string, string | number>[];
}

export interface LineChartDataPoint {
  x: string;
  y: number;
}

export interface LineChartSection {
  id: string;
  type: "line_chart";
  title: string;
  xAxis?: string;
  yAxis?: string;
  data: LineChartDataPoint[];
}

export interface TableColumn {
  key: string;
  label: string;
}

export interface TableSection {
  id: string;
  type: "table";
  title: string;
  columns?: TableColumn[];
  data: Record<string, unknown>[];
}

export interface TextSection {
  id: string;
  type: "text";
  title: string;
  content: string;
}

export type AppSection =
  | KpiCardsSection
  | DonutChartSection
  | BarChartSection
  | LineChartSection
  | TableSection
  | TextSection;

export interface AppFilter {
  id: string;
  label: string;
  options: string[];
}

export interface AppConfig {
  template: string;
  title: string;
  description: string;
  sections: AppSection[];
  filters?: AppFilter[];
}

/**
 * Parse and validate a raw app_config_json object into a typed AppConfig.
 * Returns null if the structure is invalid.
 */
export function parseAppConfig(
  raw: Record<string, unknown> | null | undefined
): AppConfig | null {
  if (!raw) return null;

  // The config may be nested under a "config" key or at the top level
  const config = (raw.config as Record<string, unknown>) ?? raw;

  if (
    typeof config.title !== "string" ||
    typeof config.description !== "string" ||
    !Array.isArray(config.sections)
  ) {
    return null;
  }

  return {
    template: (config.template as string) ?? "unknown",
    title: config.title,
    description: config.description,
    sections: config.sections as AppSection[],
    filters: Array.isArray(config.filters)
      ? (config.filters as AppFilter[])
      : undefined,
  };
}
